내정보js,연속접속기록(n일연속공부중),로그인css 회원가입css 다시 수정했습니다..!
heeeione/cote-is-really-cute pull request #11
Opened 2024-09-25 03:02 UTC by LeeSunghuck

내정보js,연속접속기록(n일연속공부중),로그인css 회원가입css 다시 수정했습니다..!

2024-09-25 04:58 UTC, wldusdn requested changes

2024-09-25 04:58 UTC, wldusdn commented on src/components/useLoginStreak.js
방문했을 때 말고 문제 풀었을 때 기준으로 체크되게 바꿀 수 있나요??

2024-09-25 09:36 UTC, heeeione requested changes

2024-09-25 09:37 UTC, wldusdn approved these changes

2024-09-29 08:21 UTC, heeeione requested changes

2024-09-29 08:21 UTC, heeeione commented on src/axios/auth.js
> +      },
axios.js 에서 헤더를 포함하여 서버에 값을 넘기기때문에 지우셔도 됩니다

2024-09-29 08:21 UTC, heeeione commented on src/pages/SignUp.js
> +      );
로컬스토리지에 백준 관련은 삭제해주세요

2024-10-01 08:17 UTC, closed without merging