🚧 wip: Edit study page/#4
heeeione/cote-is-really-cute pull request #6
Opened 2024-09-17 06:48 UTC by wldusdn

### 작업내용
- public 폴더에 이미지 추가

- menubar생성

- 학습페이지 틀만 작성

- 유저 검색 임시데이터로 틀만 작성

### 추후 작업해야할 것

- [ ] 추가된 알고리즘 문제 받아오기

- [ ] db에서 유저 정보 받아와 검색하기

- [ ] 라이벌 관계 맺고 알림기능

2024-09-20 07:09 UTC, heeeione requested changes
구현하신 기능들 이상 없으면 머지하죠

2024-09-20 07:09 UTC, heeeione commented on src/components/CategoryBtn.js
> +  const [selectedAlgorithm, setSelectedAlgorithm] = useState(null);
React.useState로 수정가능할까요?
문제될 건 없지만 전 코드들이 위의 형태로 되어 있어서요

2024-09-21 04:14 UTC, wldusdn commented on src/components/CategoryBtn.js
> +  const [selectedAlgorithm, setSelectedAlgorithm] = useState(null);
넵 알겠습니다

2024-09-22 13:43 UTC, heeeione approved these changes
👍

2024-09-30 14:01 UTC, heeeione approved these changes
수정사항만 고치고 머지하죠

2024-09-30 14:01 UTC, heeeione commented on src/utils/Items.js
> +export const items = {
여기도요

2024-09-30 14:01 UTC, heeeione commented on src/components/Header.js
> +  const { isLoggedIn, setIsLoggedIn, setEmail } = useContext(AppContext);
React.useContext로 고쳐주시면 감사하겠습니다

2024-09-30 14:02 UTC, wldusdn commented on src/components/BattleBtn.js
> +
맞습니당!

2024-09-30 14:07 UTC, wldusdn commented on src/utils/Rooms.js
> +export const rooms = [
엇 로컬은 소문자로 돼있는데 왜 대문자로 올라가있는 걸까여..?어라라

2024-09-30 14:37 UTC, heeeione commented on src/pages/PetRoom.js
> +      setLevel(1);
발표 끝나고 생각해보죠

2024-09-30 14:46 UTC, merged